package model.role;

public enum Permission {
    CONTACT_USER,
    CONTACT_CONTEXT,
    TELEPORT_TO_USER,
    MANAGE_PRIVATE_ROOM,
    ENTER_PRIVATE_ROOM,
    MUTE,
    BAN_USER,
    BAN_MODERATOR,
    ASSIGN_AREA_MANAGER,
    ASSIGN_MODERATOR,
    ASSIGN_ADMINISTRATOR,
    MANAGE_WORLDS
}
